// Generated by CoffeeScript 1.10.0
(function() {
  var BunyanLumberjackStream, LEVELS, Writable, bunyan, clone, lumberjack,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  Writable = require('stream').Writable;

  lumberjack = require('lumberjack-protocol');

  bunyan = require('bunyan');

  LEVELS = (function() {
    var answer;
    answer = {};
    ['trace', 'debug', 'info', 'warn', 'error', 'fatal'].forEach(function(level) {
      return answer[bunyan[level.toUpperCase()]] = level.toUpperCase();
    });
    return answer;
  })();

  clone = function(obj) {
    var answer, key, value;
    answer = {};
    for (key in obj) {
      value = obj[key];
      answer[key] = value;
    }
    return answer;
  };

  BunyanLumberjackStream = (function(superClass) {
    extend(BunyanLumberjackStream, superClass);

    function BunyanLumberjackStream(tlsOptions, lumberjackOptions, options) {
      var ref, ref1, ref2;
      if (lumberjackOptions == null) {
        lumberjackOptions = {};
      }
      if (options == null) {
        options = {};
      }
      BunyanLumberjackStream.__super__.constructor.call(this, {
        objectMode: true
      });
      this._client = lumberjack.client(tlsOptions, lumberjackOptions);
      this._client.on('connect', (function(_this) {
        return function(count) {
          return _this.emit('connect', count);
        };
      })(this));
      this._client.on('dropped', (function(_this) {
        return function(count) {
          return _this.emit('dropped', count);
        };
      })(this));
      this._client.on('disconnect', (function(_this) {
        return function(err) {
          return _this.emit('disconnect', err);
        };
      })(this));
      this._host = require('os').hostname();
      this._tags = (ref = options.tags) != null ? ref : ['bunyan'];
      this._type = (ref1 = options.type) != null ? ref1 : 'json';
      this._application = (ref2 = options.appName) != null ? ref2 : process.title;
      this.on('finish', (function(_this) {
        return function() {
          return _this._client.close();
        };
      })(this));
    }

    BunyanLumberjackStream.prototype._write = function(entry, encoding, done) {
      var ref, ref1, ref2;
      entry = clone(entry);
      entry.message = (ref = entry.message) != null ? ref : entry.msg;
      entry.line = entry.message;
      delete entry.msg;
      entry.bunyanLevel = entry.level;
      if (LEVELS[entry.level] != null) {
        entry.level = LEVELS[entry.level];
      }
      entry.HOSTNAME = (ref1 = entry.hostname) != null ? ref1 : this._host;
      entry.host = (ref2 = entry.hostname) != null ? ref2 : this._host;
      delete entry.time;
      delete entry.v;
      if (entry.tags == null) {
        entry.tags = this._tags;
      }
      entry.source = entry.host + "/" + this._application;
      if (this._type != null) {
        entry.type = this._type;
      }
      this._client.writeDataFrame(entry);
      return done();
    };

    return BunyanLumberjackStream;

  })(Writable);

  module.exports = function(options) {
    if (options == null) {
      options = {};
    }
    return new BunyanLumberjackStream(options.tlsOptions, options.lumberjackOptions, options);
  };

}).call(this);
